### ISSUE TITLE
[FEATURE] Add arm support (e.g. for new Apple M1 processors) for Docker image

### ISSUE THREAD

**Issue by spoonerWeb** [TYPO3-Solr/ext-solr#2891]
**Is your feature request related to a problem? Please describe.**
Currently it's not possible to run the docker container (e.g. using ddev)

**Describe the solution you'd like**
Support for arm architecture

**Additional context**
Using typo3solr/solr image in ddev context.

docker-compose.solr.yaml
```
version: '3.6'
services:
  solr:
    container_name: ddev-${DDEV_SITENAME}-solr
    image: typo3solr/ext-solr:11.0.3
    restart: "no"
    expose:
      - 8983
    labels:
      com.ddev.site-name: ${DDEV_SITENAME}
      com.ddev.approot: $DDEV_APPROOT
    environment:
      - VIRTUAL_HOST=$DDEV_HOSTNAME
      - HTTP_EXPOSE=8983
    volumes:
      - "./solr:/opt/solr/server/solr"
  web:
    links:
      - solr
```

Error when starting on M1 processor:
```
Starting Solr 
OpenJDK 64-Bit Server VM warning: Failed to reserve shared memory. (error = 1)
OpenJDK 64-Bit Server VM warning: Failed to reserve shared memory. (error = 1)
OpenJDK 64-Bit Server VM warning: Failed to reserve shared memory. (error = 1)
#
# A fatal error has been detected by the Java Runtime Environment:
#
#  SIGSEGV (0xb) at pc=0x0000004017d4a4e0, pid=23, tid=122
#
# JRE version: OpenJDK Runtime Environment 18.9 (11.0.8+10) (build 11.0.8+10)
# Java VM: OpenJDK 64-Bit Server VM 18.9 (11.0.8+10, mixed mode, tiered, compressed oops, g1 gc, linux-amd64)
# Problematic frame:
# J 97 c1 java.lang.String.isEmpty()Z java.base@11.0.8 (14 bytes) @ 0x0000004017d4a4e0 [0x0000004017d4a4c0+0x0000000000000020]
#
# No core dump will be written. Core dumps have been disabled. To enable core dumping, try "ulimit -c unlimited" before starting Java again
#
# An error report file with more information is saved as:
# /tmp/hs_err_pid23.log
Compiled method (c1)    2957   97       3       java.lang.String::isEmpty (14 bytes)
 total in heap  [0x0000004017d4a310,0x0000004017d4a688] = 888
 relocation     [0x0000004017d4a488,0x0000004017d4a4b8] = 48
 main code      [0x0000004017d4a4c0,0x0000004017d4a5e0] = 288
 stub code      [0x0000004017d4a5e0,0x0000004017d4a610] = 48
 metadata       [0x0000004017d4a610,0x0000004017d4a618] = 8
 scopes data    [0x0000004017d4a618,0x0000004017d4a630] = 24
 scopes pcs     [0x0000004017d4a630,0x0000004017d4a670] = 64
 dependencies   [0x0000004017d4a670,0x0000004017d4a678] = 8
 nul chk table  [0x0000004017d4a678,0x0000004017d4a688] = 16
Could not load hsdis-amd64.so; library not loadable; PrintAssembly is disabled
#
# If you would like to submit a bug report, please visit:
#   https://bugreport.java.com/bugreport/crash.jsp
#
qemu: uncaught target signal 6 (Aborted) - core dumped
```

**Target versions**
v10 and v11

**Comment by dkd-kaehm** [comment]
@spoonerWeb 
Thanks for reporting. 
We must check how to add platforms on docker hub.


But currently you can build the image locally, just refer to following snipped:

https://github.com/TYPO3-Solr/solr-ddev-site/blob/dd776dad79d3ca405652124bb91e5b5d1fd732be/.ddev/docker-compose.solr.yaml#L5-L8

```
version: '3.6'

services:
  solr-site:
    build:
      context:
        ../packages/ext-solr/
      dockerfile: Docker/SolrServer/Dockerfile
```

Note: EXT:solr or contents of EXT:Solr/Resources/Private/Solr must present before `ddev start` command is executed.
