### ISSUE TITLE
[BUG] Ajaxification doesn't work when page suffix with `.html` is used

### ISSUE THREAD

**Issue by simonschaufi** [TYPO3-Solr/ext-solr#3095]
**Describe the bug**
In TYPO3 10 the page type is fetched from the route configuration if given and falls back to the `type` parameter only if the url doesn't contain any information about it.

**To Reproduce**
Add the following route enhancer:

```yaml
routeEnhancers:
  PageTypeSuffix:
    type: PageType
    default: .html
    index: index
    map:
      .html: 0
```
and then call `/search.html?type=7383` and you will see that the internal page type is 0 and the full website is loaded instead of the solr ajax page type. The type parameter is ONLY considered when the page is called without `.html`.

**Expected behavior**
The page type 7383 is loaded

**Used versions (please complete the following information):**
 - TYPO3 Version: 10.4
 - EXT:solr Version: 11.1.2]

**Additional context**
The actual problem is that the ajax url is created in the search_controller.js file instead of the backend where a proper url could be created with the correct page type applied.
