### ISSUE TITLE
[BUG] All news languages are indexed for default lang (sys_language_uid=0)

### ISSUE THREAD

**Issue by Apen** [TYPO3-Solr/ext-solr#3209]
**Describe the bug**
Indexer index all news languages for default lang (sys_language_uid=0)

**To Reproduce**
1. Have a website with multiple language (en,fr,it...)
2. Just use the default news indexation
3. Check teh result in frontend

**Expected behavior**
For default language, only index news that have sys_language_uid=0

**Used versions (please complete the following information):**
 - TYPO3 Version: 11.5.5
 - EXT:solr Version: 11.5.0-beta-2

**Additional context**
I have a website with a lots of language and news. Some are translations and other are orphans.
When i index the news, solr index all the news (regarding the sys_language_uid) for the default lang (sys_language_uid=0).
So, in my core_en, i have all the news, in all the lang. And all the url of "bad" news wrong because he try to generate news link for a language that doesnt match the news.

I know a frontend is simulate so i try something like this :
```
[siteLanguage("languageId") in [0]]
	xxx.news.additionalWhereClause = sys_language_uid=0
[global]
```
But it doesnt seems to be interpreted. And i think the problem is not in the queue but in the indexer.

It work perfectly for all the other langs. For exemple, core_fr have only the "fr" news.

**Comment by dkd-kaehm** [comment]
@Apen 
Please post the site-config yaml there.

**Comment by dkd-kaehm** [comment]
@Apen Please try it with 11.5.0-beta-1
if it works as expected. IMHO it has worked in some state of 11.5.0-alpha/beta states.

**Comment by Apen** [comment]
Here is the lang config of mi website 

```
...
languages:
  -
    title: English
    enabled: true
    languageId: 0
    base: /en
    typo3Language: default
    locale: en_US.utf-8
    iso-639-1: en
    navigationTitle: English
    hreflang: en-US
    direction: ''
    flag: en-us-gb
    websiteTitle: ''
    solr_core_read: core_en
  -
    title: 'Français (France)'
    enabled: true
    languageId: 1
    base: /fr-fr
    typo3Language: fr
    locale: fr_FR.utf-8
    iso-639-1: fr
    navigationTitle: Français
    hreflang: fr-FR
    direction: ''
    fallbackType: strict
    fallbacks: '0'
    flag: fr
    websiteTitle: ''
    solr_core_read: core_fr
  -
    title: Deutsch
    enabled: false
    languageId: 2
    base: /de
    typo3Language: de
    locale: de_DE.utf-8
    iso-639-1: de
    navigationTitle: Deutsch
    hreflang: de-DE
    direction: ''
    fallbackType: strict
    fallbacks: '0'
    flag: de
    websiteTitle: ''
    solr_enabled_read: false
...
solr_enabled_read: true
solr_host_read: typo3-solr-server
solr_path_read: /
solr_port_read: '8983'
solr_scheme_read: http
solr_use_write_connection: false
```
