### ISSUE TITLE
[BUG] Logged out from backend if a site language has no record that fit

### ISSUE THREAD

**Issue by Raidri** [TYPO3-Solr/ext-solr#3326]
**Describe the bug**
I've a site config with 3 languages:
```yaml
     -
        title: English Int
        enabled: true
        languageId: '0'
        base: /en/
        typo3Language: default
        locale: 'en_001.UTF-8,en_001,en_GB.UTF-8,en_GB'
        iso-639-1: en
        navigationTitle: English Int
        hreflang: en
        direction: ltr
        flag: en-us-gb
        solr_core_read: en
    -
        title: German
        enabled: true
        languageId: '3'
        base: /de/
        typo3Language: de
        locale: 'de_DE.UTF-8,de_DE'
        iso-639-1: de
        navigationTitle: Germany
        hreflang: de-DE
        direction: ltr
        fallbackType: strict
        flag: de
        solr_core_read: de
   -   
        title: Polish
        enabled: true
        languageId: '11'
        base: /pl/
        typo3Language: pl
        locale: 'pl_PL.UTF-8,pl_PL'
        iso-639-1: pl
        navigationTitle: Poland
        hreflang: pl-PL
        direction: ltr
        fallbackType: strict
        fallback: ''
        flag: pl
        solr_core_read: pl
```

Then I've a extbase model which has the default and the german language but no translation for the polish.
If I index the record I get the following error
`Error: Call to a member function getLanguageOverlay() on null in /var/www/html/vendor/apache-solr-for-typo3/solr/Classes/IndexQueue/Indexer.php:272`
and will logged out from the TYPO3 Backend.
The englisch and german data were indexed.

**Used versions (please complete the following information):**
 - TYPO3 Version: 11.5.14
 - Browser: any
 - EXT:solr Version: 11.5-rc3
 - Used Apache Solr Version: 8.11.1
 - PHP Version: 8.1
 - MySQL Version: 8.0

Related: #3246
