### ISSUE TITLE
[BUG] typo3 solr does not support the field value 'solr_path_read' if we have solr_core_read in languages tab

### ISSUE THREAD

**Issue by cwplus** [TYPO3-Solr/ext-solr#3348]
**Describe the bug**
In our company we multiple versions of Solr, like:
http://solr01.bas.etnic.be:8990/solr852/#/  for typo3 v10 et maybe typo3 v11 ( testing)
http://solr01.bas.etnic.be:8983/solr662/#/  for typo3 v8
http://solr01.bas.etnic.be:8983/solr481/#/  for typo3 old versions

we use 3 langages by site ( FR, EN, and NL )

all these solr versions are running in the same tomcat server.

here is the yaml config of our typo3 v11 test server:

```yaml
base: /
languages:
  -
    title: FR
    enabled: true
    languageId: 0
    base: /
    typo3Language: fr
    locale: fr_FR.UTF-8
    iso-639-1: fr
    navigationTitle: FR
    hreflang: fr-FR
    direction: ltr
    flag: fr
    websiteTitle: ''
    solr_core_read: core_cfwb
  -
    title: EN
    enabled: true
    base: /en/
    typo3Language: default
    locale: en_US.utf8
    iso-639-1: en
    websiteTitle: EN
    navigationTitle: EN
    hreflang: en
    direction: ltr
    fallbackType: fallback
    fallbacks: '0'
    flag: en-us-gb
    languageId: 1
    solr_core_read: core_cfwb_en
  -
    title: NL
    enabled: true
    languageId: 2
    base: /nl/
    typo3Language: nl
    locale: nl_NL.UTF-8
    iso-639-1: nl
    navigationTitle: NL
    hreflang: nl
    direction: ltr
    fallbackType: fallback
    fallbacks: '0'
    flag: nl
    websiteTitle: ''
    solr_core_read: core_cfwb_nl
rootPageId: 1
solr_enabled_read: true
solr_host_read: 'solr01.bas.etnic.be'
solr_path_read: '/solr852/'
solr_port_read: '8990'
solr_scheme_read: http
solr_use_write_connection: false
websiteTitle: 'TYPO3 Introduction Package'
```

The problem is that the Typo3 solr plugin (v11) does not support the field value 'solr_path_read'

**Screenshots**
with this site config, we must have the following solr link:
http://solr01.bas.etnic.be:8990/solr852/core_cfwb/
not :
solr852](http://solr01.bas.etnic.be:8990/solr/core_cfwb/

![Screenshot_109](https://user-images.githubusercontent.com/5727109/191242140-93b96e47-e167-48f9-a9f0-a116693c20ff.png)
![Screenshot_108](https://user-images.githubusercontent.com/5727109/191242145-d7829e1c-d53e-41b0-bee7-728f3c6f9db8.png)

**Used versions:**
 - TYPO3 Version: [11.5.4]
 - Browser: [firefox]
 - EXT:solr Version: [11.5.0]
 - Used Apache Solr Version: [ 8.5.2]
 - PHP Version: [ 8.0]
 - MySQL Version: [8.0]
