### ISSUE TITLE
[BUG] Autosuggest from the Example not Working

### ISSUE THREAD

**Issue by Finulin** [TYPO3-Solr/ext-solr#3393]
Autosuggest from the Example not Working.

Error:
(1/1) #1298012500 TYPO3\CMS\Extbase\Mvc\Controller\Exception\RequiredArgumentMissingException
Required argument "queryString" is not set for ApacheSolrForTypo3\Solr\Controller\SuggestController->suggest.

The Url contain the queryString:
?tx_solr[callback]=jQuery311008454058125288455_166…390559&tx_solr%5BqueryString%5D=w&_=1667564390560

RouteEnhancer is set:
```
routeEnhancers:
  PageTypeSuffix:
    type: PageType
    map:
      suggest.json: 7384
```
Solr-Extension-Version 11.5.0
