### ISSUE TITLE
[BUG] wrong indexing behaviour with fallbackType: free

### ISSUE THREAD

**Issue by abohntek** [TYPO3-Solr/ext-solr#3560]
**Describe the bug**
I have a problem with the correct indexing behaviour for ext:news records with fallbackType: free and 3 langs set. I have en, dk and de as languages set ( core_dk, core_de and core_en for the solr cores). But inside core_en dk, de & en news getting indexed! Expected behaviour should be that only en news are indexed. If I remove the fallbackType: free in the site config then only en news get indexed correctly inside core_en. 

**To Reproduce**

- solr base & news ts inclusion (see attached img)
- 3 news in all 3 languages (total 9 records see attached img)
- fallbackType free for dk & de
- for dk & de indexing is correct
- for en (default lang) alle records in all languages are getting indexed (see attached img). 

**Expected behavior**
for en only en news shall be indexed or found via frontend search.

**Screenshots**
![sole-ddev-templates](https://user-images.githubusercontent.com/41919860/228246752-846000fa-f01e-47b9-8530-b824f03b4132.png)
![news-list](https://user-images.githubusercontent.com/41919860/228246765-d38a0bd0-6480-41a2-93cd-2bdeb8692224.png)
![wrong-indexing](https://user-images.githubusercontent.com/41919860/228246767-637a0d9f-5453-4477-85b3-0189d9f3d5c8.png)

**Used versions:**
 - Setup with https://github.com/TYPO3-Solr/solr-ddev-site
 - TYPO3 Version: 11.5.25
 - EXT:solr Version: tested with 11.5.x-dev & 11.5.1
 - ext:news: tested with v9.4 to v11.0

DDEV Database Dump:

[solr-ddev-sites-data.sql.gz](https://github.com/TYPO3-Solr/ext-solr/files/11089753/solr-ddev-sites-data.sql.gz)

**Comment by dmitryd** [comment]
@abohntek It could help if you posed your site config. I think you have `fallbacks` set there. As long as you have `fallbacks` set in site config, you will get the behavior you describe. With `fallbacks` set, `fallbackType` does not work exactly as described in the official documentation. You will always get the record in the fallback language if `fallback` is enabled.

**Comment by dkd-kaehm** [comment]
@abohntek 
Is default site config from solr-ddev-site used in your example?

> @abohntek It could help if you posed your site config. I think you have `fallbacks` set there. As long as you have `fallbacks` set in site config, you will get the behavior you describe. With `fallbacks` set, `fallbackType` does not work exactly as described in the official documentation. You will always get the record in the fallback language if `fallback` is enabled.

**Comment by abohntek** [comment]
Yes, I had fallbacks set. But after removing fallbacks it still does not work as exptected. Attached my currently used site config without fallbacks.

[config.txt](https://github.com/TYPO3-Solr/ext-solr/files/12646951/config.txt)

**Comment by schliesser** [comment]
Hey, I have the same problem in a project since we changed fallbackType from strict to free. We have no fallbacks set for our 13 translations.

Records are getting indexed for all languages, but are duplicated to the default language. When clean the index, queue and switch to  fallbackType: strict, all works perfectly fine.

```yaml
solr_enabled_read: true
solr_host_read: relaunch.ddev.site
solr_path_read: /solr/
solr_port_read: '8984'
solr_scheme_read: https
solr_use_write_connection: false

languages:
  - title: German
    enabled: true
    languageId: 0
    base: '/'
    typo3Language: de
    locale: de_DE.utf8
    iso-639-1: de
    navigationTitle: German
    hreflang: de-DE
    direction: ltr
    flag: de
    websiteTitle: ''
    solr_core_read: core_de
  - title: English
    enabled: true
    base: https://eu.relaunch.ddev.site/
    typo3Language: default
    locale: en_EU
    iso-639-1: en
    websiteTitle: ''
    navigationTitle: English
    hreflang: en
    direction: ltr
    fallbackType: free
    fallbacks: ''
    flag: eu
    languageId: 1
    solr_core_read: core_eu
  - title: Czech
    enabled: true
    base: https://cz.relaunch.ddev.site/
    typo3Language: cs
    locale: cs_CZ
    iso-639-1: cs
    websiteTitle: ''
    navigationTitle: Czech
    hreflang: cs-CZ
    direction: ''
    fallbackType: free
    fallbacks: ''
    flag: cz
    languageId: 10
    solr_core_read: core_cs
```

The Typoscript config for our FAQ records:

```typoscript
plugin.tx_solr.index.queue {
  faq = 1
  faq {
    type = tx_rbfaq_domain_model_faq

    fields {
      type_stringS = TEXT
      type_stringS.value = FAQ

      abstract = question
      title = question

      content = SOLR_CONTENT
      content {
        cObject = COA
        cObject {
          10 = TEXT
          10 {
            field = answer
            noTrimWrap = || |
          }
        }
      }

      product_stringM = SOLR_RELATION
      product_stringM {
        localField = product
        relationTableSortingField = sorting
        multiValue = 1
      }

      productcategory_stringM = SOLR_RELATION
      productcategory_stringM {
        localField = productcategory
        relationTableSortingField = sorting
        multiValue = 1
      }

      url = TEXT
      url {
        typolink {
          parameter = 252
          additionalParams = &faq={field:uid}&L={field:__solr_index_language}
          additionalParams.insertData = 1
          returnLast = url
        }
      }

    }
  }
}
```

I noticed a difference in the queue between strict and free:

With `fallbackType: strict` the Initializer adds 97 FAQ records. With `fallbackType: free` the initializer add 1229 FAQ records to the indexer queue.
In case of `free` an additional AndWhere with all sys_language_uids is added:
```sql
SELECT '1' as root, 'tx_rbfaq_domain_model_faq' AS item_type, uid AS item_uid, 'faq' as indexing_configuration, 0 AS indexing_priority, GREATEST(starttime,tstamp) AS changed, "" as errors FROM tx_rbfaq_domain_model_faq WHERE pid IN(1,2,4,]...]) AND deleted = 0 AND hidden = 0 AND (endtime > 1695032735 OR endtime = 0) AND (sys_language_uid = 0 OR sys_language_uid = -1 OR sys_language_uid IN( 1,2,3,4,5,6,7,8,9,10,11,12,13) OR l10n_parent = 0) AND t3ver_wsid = 0 
```

So far that should be fine, but then during indexing, the records with a sys_language_uid other than 0,-1 are also added to language = 0.
![image](https://github.com/TYPO3-Solr/ext-solr/assets/11655823/2ed7b4d6-9378-483a-a19a-474f33c92f1d)

In case of `fallbackType: free` the `getItemRecordOverlayed()` method should return null, if `$language` is `0`, but sys_language_uid is not.

Adding this check to `getItemRecordOverlayed()` works for me: 
```php
        // skip translated records for default language within "free content mode"-languages
        if ($language === 0
            && isset($languageField)
            && (int)($itemRecord[$languageField] ?? null) !== $language
            && $this->isLanguageInAFreeContentMode($item, (int)($itemRecord[$languageField] ?? null))
        ) {
            return null;
        }
```

I think we can skip the condition:
`&& $this->isLanguageInAFreeContentMode($item, (int)($itemRecord[$languageField] ?? null))` but not sure about side effects for other configs.
