### ISSUE TITLE
[BUG] Operation not permitted (ix-file-permissions.sh)

### ISSUE THREAD

**Issue by varioous** [TYPO3-Solr/ext-solr#3837]
When starting solr service the start fails everytime with: 

`ddev logs -s solr
/opt/solr/docker/scripts/solr-foreground: running /docker-entrypoint-initdb.d/as-sudo/fix-file-permissions.sh
chown: changing ownership of '/var/solr/data/cores': Operation not permitted`

.ddev-docker-compose.solr.yaml
```yaml
services:
  solr:
    container_name: ddev-${DDEV_SITENAME}-solr
    image: typo3solr/ext-solr:12.0.x-dev
    ports:
      - 8983
    labels:
      com.ddev.site-name: ${DDEV_SITENAME}
      com.ddev.approot: $DDEV_APPROOT
    environment:
      - VIRTUAL_HOST=$DDEV_HOSTNAME
      - HTTP_EXPOSE=8983
    volumes:
      - ./solr/cores:/var/solr/data/cores
      - solr:/var/solr
  web:
    links:
      - solr

volumes:
  solr:
```

**Expected behavior**
Solr started successfully

**Used versions:**
 - TYPO3 Version:12.4
 - EXT:solr Version: 12.0.0

**Additional context**
Setup: Windows + Docker-Desktop + WSL2
