### ISSUE TITLE
[BUG] jquery-ui-custom refers to non-existing path

### ISSUE THREAD

**Issue by dmitryd** [TYPO3-Solr/ext-solr#3896]
**Describe the bug**

In `Resources/Public/Css/JQueryUi/jquery-ui.custom.css`:

```css
.ui-widget-content { border: 1px solid #dddddd; background: #f7f7f7 url(../../Images/JQueryUi/ui-bg_highlight-hard_100_f7f7f7_1x100.png) 50% top repeat-x; color: #312e25; }
.ui-widget-header { border: 1px solid #d4ccb0; background: #ece8da url(../../Images/JQueryUi/ui-bg_gloss-wave_100_ece8da_500x100.png) 50% 50% repeat-x; color: #433f38; font-weight: bold; }
```
and more.

It is two levels up but the folder is not there. It is actually three levels up:

<img src="https://github.com/TYPO3-Solr/ext-solr/assets/306133/15264a39-8988-4f51-aabf-e9748f04f346" height="500"/>

We build resources ourselves using webpack. Webpack fails because it cannot find those images.

**Used versions (please complete the following information):**
 - TYPO3 Version: 12.4.8
 - EXT:solr Version: 12.0.1
