### ISSUE TITLE
[BUG] Plugin "postbigrequest" is added, but does not work

### ISSUE THREAD

**Issue by andreaswolf** [TYPO3-Solr/ext-solr#3914]
**Describe the bug**
`SolrConnection::getClient()` adds the `postbigrequest` plugin to the Solarium Client instance. The plugin, however, registers itself as an event listener only if the event dispatcher instance comes from symfony/event-dispatcher, see https://github.com/solariumphp/solarium/blob/13995b65b1067f25497eee8434d87c4bb1b24bf4/src/Plugin/PostBigRequest.php#L99.

This does not work, because the passed EventDispatcher is compatible to PSR's EventDispatcherInterface, but not a Symfony EventDispatcher instance (since TYPO3 ships its own EventDispatcher).

**To Reproduce**

Perform a big request, e.g. by adding lots of facets that are passed to Solr with the request. The request will fail if its URL becomes too long, in our case it was > 8000 chars. This should normally be prevented by the postbigrequest plugin. 

**Possible fix**

Registering the plugin's event listener via the Services.yaml file in EXT:solr:

```yaml
services:
# […]
  Solarium\Plugin\PostBigRequest:
    tags:
      - name: event.listener
        method: preExecuteRequest
        identifier: solr.PostBigRequest
        event: Solarium\Core\Event\PreExecuteRequest
```

**Used versions (please complete the following information):**
 - TYPO3 Version: 11.5.33
 - Browser: n/a
 - EXT:solr Version: 11
 - Used Apache Solr Version: n/a
 - PHP Version: 8.2.0
 - MySQL Version: n/a

**Additional context**
