### ISSUE TITLE
[FEATURE] cHash excludedParameters restriction and canonical urls

### ISSUE THREAD

**Issue by trokohl** [TYPO3-Solr/ext-solr#4086]
At the moment, all parameters beginning with tx_solr are excluded form the cHash by the entries in TYPO3_CONF_VARS->FE->cacheHash->excludedParameters.

This hard restriction also means that the canonical-url does not take on any parameters for generating the address.

For example, if I define categories for certain aspects such as a location, these are not taken into account when creating the URL.

In my example, I have defined the following routes.

```
    routes:
      -
        routePath: '<?/country/{country}?><?/city/{city}?><?/category/{category}?><?/status/{status}?>'
        _arguments:
          category: filter/category
          status: filter/status
          city: filter/city
          country: filter/country
```

For example, there is the valid URL:

https://mydomain.de/search/city/berlin

This url should show all content for Berlin and therefore be indexed by google.

The canonical URL is currently:

`<link rel="canonical" href="https://mydomain.de/search/"/>`

Which is not my desired result.
Maybe you can make the rule adjustable. My workaround at the moment is:

```

  $excludedParameters = $GLOBALS['TYPO3_CONF_VARS']['FE']['cacheHash']['excludedParameters'];
  $newExcludedParameters = [];
  foreach($excludedParameters as $param) {
    if(!str_contains($param,'tx_solr')) {
      $newExcludedParameters[] = $param;
    }
  }
  $newExcludedParameters[] = "^tx_solr[q";
  $GLOBALS['TYPO3_CONF_VARS']['FE']['cacheHash']['excludedParameters'] = $newExcludedParameters;

```
If I remove the basic.pluginNamespaces setting, the restriction still remains.

TYPO3 11.5
SOLR 11.5.6
