### ISSUE TITLE
[BUG] Unable to register a custom facet package with FacetRegistry

### ISSUE THREAD

**Issue by b3nkai** [TYPO3-Solr/ext-solr#4280]
**Describe the bug**

**To Reproduce**

Declare a custom facet package:

```
$facetRegistry = GeneralUtility::makeInstance(FacetRegistry::class);
$facetRegistry->registerPackage(
    CustomFacetPackage::class,
    'customfacet'
);
```

Use this facet type:

```
plugin.tx_solr {
    search {
        faceting = 1
        faceting {
            facets {
                customfield {
                    label = Custom facet
                    field = customfield_stringS
                    type = customfacet
                    partialName = CustomFacet
                }
          }
     }
}
```

**Expected behavior**

We expect to receive the CustomFacet object in the CustomFacet template but we receive the default "OptionFacet".

**Reason**

The FacetRegistry extends the AbstractClassRegistry class which implements the TYPO3 SingletonInterface.
As TYPO3 12 now use the Symfony container manager, this class must not be declared as shared in Services.yml.

**Solution**

Exclude the FacetRegistry class in  Services.yml so won't be shared:
```
  facets:
    namespace: ApacheSolrForTypo3\Solr\Domain\Search\ResultSet\Facets\
    resource: '../Classes/Domain/Search/ResultSet/Facets/*'
    exclude:
      - '../Classes/Domain/Search/ResultSet/Facets/{OptionBased/Hierarchy/Node.php,*/Abstract*}'
      - '../Classes/Domain/Search/ResultSet/Facets/*/*/*Facet.php'
      - '../Classes/Domain/Search/ResultSet/Facets/RangeBased/*/*RangeCount.php'
      - '../Classes/Domain/Search/ResultSet/Facets/FacetRegistry.php'
    public: true
    autowire: true
    shared: false
```

**Used versions (please complete the following information):**
 - TYPO3 Version: [e.g. 12.4.0]
 - EXT:solr Version: [e.g. 12.0.5]
 - Used Apache Solr Version: [e.g. 9.3.0]
 - PHP Version: [e.g. 8.2.x]
