### ISSUE TITLE
[BUG] routeEnhancer is broken with PageTypeSuffix

### ISSUE THREAD

**Issue by dogawaf** [TYPO3-Solr/ext-solr#4289]
**Describe the bug**

When a PageTypeSuffix is used in the site config.yaml, in order to suffix url with ".html", the Solr's routeEnhancer generates brokens url for filters.

**To Reproduce**

Given this config in the site routing : 

```
routeEnhancers:
  PageTypeSuffix:
    type: CustomPageType
    default: .html
    index: index
```

And the SolrFacetMaskAndCombineEnhancer config given as example in the documentation:

```
routeEnhancers:
  products:
    type: SolrFacetMaskAndCombineEnhancer
    limitToPages:
      - 42
    extensionKey: tx_solr
    routePath: '/{productType}'
    _arguments:
      productType: filter-productType
    requirements:
      productType: '.*'
```

**Expected behavior**

Url for filters should be generated with `.html` at the end, and be decoded without saving the `.html` into the filter value.

**Used versions (please complete the following information):**
 - TYPO3 Version: 12.4.22
 - EXT:solr Version: 12.0.5 
 - PHP Version: 8.2
